### ISSUE TITLE
Hang in MutationsBatcher.mutate()

### ISSUE THREAD

**Issue by patjakdev** [googleapis/python-bigtable#949] opened 2024-04-01 19:21 UTC
#### Environment details

  - OS type and version: Mac OS X 14.1.2, Ubuntu 22.04
  - Python version: 3.10.13
  - pip version: N/A
  - `google-cloud-bigtable` version: 2.23.0

#### Steps to reproduce

Recently, we started seeing this usage of the MutationsBatcher hang indefinitely in `mutate()`. This issue seems to be reproducible both in my local development environment (Mac) as well as in our deployed dev environment (Linux).

Based on the stack traces I included below, I'm guessing there's some problem with the creation of the gRPC channel to perform the flush but it's unclear to me how to get any insight into what might be going on there.

#### Code example

```python
    def _on_batch_completed(self, statuses: Sequence[Status]) -> None:
            logger.debug(f"Completed write batch of size {len(statuses)}: {statuses}")

    def store_features(self, entity_type: str, entities: pd.DataFrame) -> None:
        table = "ml_features_cases"
        packer = msgpack.Packer()
        with MutationsBatcher(table, batch_completed_callback=self._on_batch_completed) as batch:
            for index, *values in entities.itertuples(name=None):
                row = table.direct_row(index.encode("utf-8"))

                for column_name, value in zip(entities.columns.values, values):
                    # ... encode data into variable named encoded_value
                    row.set_cell("features", column_name.encode(), encoded_value)

                batch.mutate(row)
```

#### Stack trace
```
Thread 0x000000029d037000 (most recent call first):

 File "/Users/patrick/Library/Caches/pypoetry/virtualenvs/realtime-dagster-wbtued84-py3.10/lib/python3.10/site-packages/grpc/_channel.py", line 1972 in __init__
 File "/Users/patrick/Library/Caches/pypoetry/virtualenvs/realtime-dagster-wbtued84-py3.10/lib/python3.10/site-packages/grpc/__init__.py", line 2107 in secure_channel
 File "/Users/patrick/Library/Caches/pypoetry/virtualenvs/realtime-dagster-wbtued84-py3.10/lib/python3.10/site-packages/google/api_core/grpc_helpers.py", line 386 in create_channel
 File "/Users/patrick/Library/Caches/pypoetry/virtualenvs/realtime-dagster-wbtued84-py3.10/lib/python3.10/site-packages/google/cloud/bigtable_v2/services/bigtable/transports/grpc.py", line 217 in create_channel
 File "/Users/patrick/Library/Caches/pypoetry/virtualenvs/realtime-dagster-wbtued84-py3.10/lib/python3.10/site-packages/google/cloud/bigtable/client.py", line 285 in _create_gapic_client_channel
 File "/Users/patrick/Library/Caches/pypoetry/virtualenvs/realtime-dagster-wbtued84-py3.10/lib/python3.10/site-packages/google/cloud/bigtable/client.py", line 332 in table_data_client
 File "/Users/patrick/Library/Caches/pypoetry/virtualenvs/realtime-dagster-wbtued84-py3.10/lib/python3.10/site-packages/google/cloud/bigtable/table.py", line 160 in name
 File "/Users/patrick/Library/Caches/pypoetry/virtualenvs/realtime-dagster-wbtued84-py3.10/lib/python3.10/site-packages/google/cloud/bigtable/table.py", line 724 in mutate_rows
 File "/Users/patrick/Library/Caches/pypoetry/virtualenvs/realtime-dagster-wbtued84-py3.10/lib/python3.10/site-packages/google/cloud/bigtable/batcher.py", line 385 in _flush_rows
 File "/Users/patrick/.pyenv/versions/3.10.13/lib/python3.10/concurrent/futures/thread.py", line 58 in run
 File "/Users/patrick/.pyenv/versions/3.10.13/lib/python3.10/concurrent/futures/thread.py", line 83 in _worker
 File "/Users/patrick/.pyenv/versions/3.10.13/lib/python3.10/threading.py", line 953 in run
 File "/Users/patrick/.pyenv/versions/3.10.13/lib/python3.10/threading.py", line 1016 in _bootstrap_inner
 File "/Users/patrick/.pyenv/versions/3.10.13/lib/python3.10/threading.py", line 973 in _bootstrap

Thread 0x000000029c02b000 (most recent call first):

 File "", line 1074 in get_data
 File "/Users/patrick/.pyenv/versions/3.10.13/lib/python3.10/pkgutil.py", line 639 in get_data
 File "/Users/patrick/Library/Caches/pypoetry/virtualenvs/realtime-dagster-wbtued84-py3.10/lib/python3.10/site-packages/grpc/_channel.py", line 1972 in __init__
 File "/Users/patrick/Library/Caches/pypoetry/virtualenvs/realtime-dagster-wbtued84-py3.10/lib/python3.10/site-packages/grpc/__init__.py", line 2107 in secure_channel
 File "/Users/patrick/Library/Caches/pypoetry/virtualenvs/realtime-dagster-wbtued84-py3.10/lib/python3.10/site-packages/google/api_core/grpc_helpers.py", line 386 in create_channel
 File "/Users/patrick/Library/Caches/pypoetry/virtualenvs/realtime-dagster-wbtued84-py3.10/lib/python3.10/site-packages/google/cloud/bigtable_v2/services/bigtable/transports/grpc.py", line 217 in create_channel
 File "/Users/patrick/Library/Caches/pypoetry/virtualenvs/realtime-dagster-wbtued84-py3.10/lib/python3.10/site-packages/google/cloud/bigtable/client.py", line 285 in _create_gapic_client_channel
 File "/Users/patrick/Library/Caches/pypoetry/virtualenvs/realtime-dagster-wbtued84-py3.10/lib/python3.10/site-packages/google/cloud/bigtable/client.py", line 332 in table_data_client
 File "/Users/patrick/Library/Caches/pypoetry/virtualenvs/realtime-dagster-wbtued84-py3.10/lib/python3.10/site-packages/google/cloud/bigtable/table.py", line 160 in name
 File "/Users/patrick/Library/Caches/pypoetry/virtualenvs/realtime-dagster-wbtued84-py3.10/lib/python3.10/site-packages/google/cloud/bigtable/table.py", line 724 in mutate_rows
 File "/Users/patrick/Library/Caches/pypoetry/virtualenvs/realtime-dagster-wbtued84-py3.10/lib/python3.10/site-packages/google/cloud/bigtable/batcher.py", line 385 in _flush_rows
 File "/Users/patrick/.pyenv/versions/3.10.13/lib/python3.10/concurrent/futures/thread.py", line 58 in run
 File "/Users/patrick/.pyenv/versions/3.10.13/lib/python3.10/concurrent/futures/thread.py", line 83 in _worker
 File "/Users/patrick/.pyenv/versions/3.10.13/lib/python3.10/threading.py", line 953 in run
 File "/Users/patrick/.pyenv/versions/3.10.13/lib/python3.10/threading.py", line 1016 in _bootstrap_inner
 File "/Users/patrick/.pyenv/versions/3.10.13/lib/python3.10/threading.py", line 973 in _bootstrap

Current thread 0x00000001d6c01ec0 (most recent call first):

 File "/Users/patrick/.pyenv/versions/3.10.13/lib/python3.10/threading.py", line 320 in wait
 File "/Users/patrick/.pyenv/versions/3.10.13/lib/python3.10/threading.py", line 607 in wait
 File "/Users/patrick/.pyenv/versions/3.10.13/lib/python3.10/threading.py", line 940 in start
 File "/Users/patrick/.pyenv/versions/3.10.13/lib/python3.10/concurrent/futures/thread.py", line 199 in _adjust_thread_count
 File "/Users/patrick/.pyenv/versions/3.10.13/lib/python3.10/concurrent/futures/thread.py", line 176 in submit
 File "/Users/patrick/Library/Caches/pypoetry/virtualenvs/realtime-dagster-wbtued84-py3.10/lib/python3.10/site-packages/google/cloud/bigtable/batcher.py", line 340 in _flush_async
 File "/Users/patrick/Library/Caches/pypoetry/virtualenvs/realtime-dagster-wbtued84-py3.10/lib/python3.10/site-packages/google/cloud/bigtable/batcher.py", line 266 in mutate
 File "/Users/patrick/src/Apella-Technology/realtime-dags/case_forecasting_baseline/feature_store/feature_store.py", line 138 in store_features
 File "/Users/patrick/src/Apella-Technology/realtime-dags/case_forecasting_baseline/dags/ops/feature_calculation.py", line 137 in store_features
 File "/Users/patrick/Library/Caches/pypoetry/virtualenvs/realtime-dagster-wbtued84-py3.10/lib/python3.10/site-packages/dagster/_core/execution/plan/compute_generator.py", line 125 in invoke_compute_fn
 File "/Users/patrick/Library/Caches/pypoetry/virtualenvs/realtime-dagster-wbtued84-py3.10/lib/python3.10/site-packages/dagster/_core/execution/plan/compute_generator.py", line 131 in _coerce_op_compute_fn_to_iterator
 File "/Users/patrick/Library/Caches/pypoetry/virtualenvs/realtime-dagster-wbtued84-py3.10/lib/python3.10/site-packages/dagster/_utils/__init__.py", line 465 in iterate_with_context
 File "/Users/patrick/Library/Caches/pypoetry/virtualenvs/realtime-dagster-wbtued84-py3.10/lib/python3.10/site-packages/dagster/_core/execution/plan/compute.py", line 181 in _yield_compute_results
 File "/Users/patrick/Library/Caches/pypoetry/virtualenvs/realtime-dagster-wbtued84-py3.10/lib/python3.10/site-packages/dagster/_core/execution/plan/compute.py", line 212 in execute_core_compute
 File "/Users/patrick/Library/Caches/pypoetry/virtualenvs/realtime-dagster-wbtued84-py3.10/lib/python3.10/site-packages/dagster/_core/execution/plan/execute_step.py", line 95 in _process_asset_results_to_events
 File "/Users/patrick/Library/Caches/pypoetry/virtualenvs/realtime-dagster-wbtued84-py3.10/lib/python3.10/site-packages/dagster/_core/execution/plan/execute_step.py", line 160 in _step_output_error_checked_user_event_sequence
 File "/Users/patrick/Library/Caches/pypoetry/virtualenvs/realtime-dagster-wbtued84-py3.10/lib/python3.10/site-packages/dagster/_core/execution/plan/execute_step.py", line 478 in core_dagster_event_sequence_for_step
 File "/Users/patrick/Library/Caches/pypoetry/virtualenvs/realtime-dagster-wbtued84-py3.10/lib/python3.10/site-packages/dagster/_core/execution/plan/execute_plan.py", line 286 in dagster_event_sequence_for_step
 File "/Users/patrick/Library/Caches/pypoetry/virtualenvs/realtime-dagster-wbtued84-py3.10/lib/python3.10/site-packages/dagster/_core/execution/plan/execute_plan.py", line 121 in inner_plan_execution_iterator
 File "/Users/patrick/Library/Caches/pypoetry/virtualenvs/realtime-dagster-wbtued84-py3.10/lib/python3.10/site-packages/dagster/_core/executor/in_process.py", line 26 in inprocess_execution_iterator
 File "/Users/patrick/Library/Caches/pypoetry/virtualenvs/realtime-dagster-wbtued84-py3.10/lib/python3.10/site-packages/dagster/_core/execution/api.py", line 875 in __iter__
 File "/Users/patrick/Library/Caches/pypoetry/virtualenvs/realtime-dagster-wbtued84-py3.10/lib/python3.10/site-packages/dagster/_core/executor/in_process.py", line 55 in execute
 File "/Users/patrick/Library/Caches/pypoetry/virtualenvs/realtime-dagster-wbtued84-py3.10/lib/python3.10/site-packages/dagster/_core/execution/api.py", line 764 in job_execution_iterator
 File "/Users/patrick/Library/Caches/pypoetry/virtualenvs/realtime-dagster-wbtued84-py3.10/lib/python3.10/site-packages/dagster/_core/execution/api.py", line 875 in __iter__
 File "/Users/patrick/Library/Caches/pypoetry/virtualenvs/realtime-dagster-wbtued84-py3.10/lib/python3.10/site-packages/dagster/_grpc/impl.py", line 152 in core_execute_run
 File "/Users/patrick/Library/Caches/pypoetry/virtualenvs/realtime-dagster-wbtued84-py3.10/lib/python3.10/site-packages/dagster/_grpc/impl.py", line 242 in _run_in_subprocess
 File "/Users/patrick/Library/Caches/pypoetry/virtualenvs/realtime-dagster-wbtued84-py3.10/lib/python3.10/site-packages/dagster/_grpc/impl.py", line 266 in start_run_in_subprocess
 File "/Users/patrick/.pyenv/versions/3.10.13/lib/python3.10/multiprocessing/process.py", line 108 in run
 File "/Users/patrick/.pyenv/versions/3.10.13/lib/python3.10/multiprocessing/process.py", line 314 in _bootstrap
 File "/Users/patrick/.pyenv/versions/3.10.13/lib/python3.10/multiprocessing/spawn.py", line 129 in _main
 File "/Users/patrick/.pyenv/versions/3.10.13/lib/python3.10/multiprocessing/spawn.py", line 116 in spawn_main
 File "", line 1 in 
```

**Comment by patjakdev** [comment] 2024-04-01 19:29
I should add that this hang is not deterministic. It happens about 50% of the time that the code runs.

**Comment by patjakdev** [comment] 2024-04-01 23:51
A bit more information. This issue only occurs with `google-api-core` >= 2.17.0.

Given that `google/api_core/grpc_helpers.py` appears near the problematic area in the callstack, I think this may be in an issue in that library.

**Comment by daniel-sanche** [comment] 2024-04-04 23:52
I was able to reproduce the issue. It looks like it comes up when [table.name](https://github.com/googleapis/python-bigtable/blob/1cc1ff72ac74c5031a142ba88cfea112e368bb6c/google/cloud/bigtable/table.py#L724) is called in a background thread. `.name` ends up [calling](https://github.com/googleapis/python-bigtable/blob/1cc1ff72ac74c5031a142ba88cfea112e368bb6c/google/cloud/bigtable/table.py#L160) `_client.table_data_client`, which [builds a new transport](https://github.com/googleapis/python-bigtable/blob/1cc1ff72ac74c5031a142ba88cfea112e368bb6c/google/cloud/bigtable/client.py#L332) if it's being called the first time. It looks like when it's constructed for the first time in a background thread, it sometimes (always?) locks up. Calling `table.name` before starting the MutationsBatcher seems to prevent this issue

Your observation on it being related to `google-api-core==2.17.0` was a good one. It looks like this is hanging on [this `ssl_credentials` change](https://github.com/googleapis/python-api-core/commit/94726e739698035b00667983f854c600252abd28#r140639644) added in 2.17.0

@parthea let me know how you want to proceed. I can probably make some patches to fix this issue on the bigtable side, but it's probably better to fix this in api_core

**Comment by parthea** [comment] 2024-04-05 11:06
@daniel-sanche 

Can you share the code that you used to create the issue, and the version of gRPC that was used? I can check to see if this is an issue in other clients as well.

**Comment by daniel-sanche** [comment] 2024-04-05 17:50
I reproduced it yesterday using similar code to Patrick above. But this simpler, more generic sample also hangs:

```
import google.cloud.bigtable
import concurrent.futures

def bg_worker():
    print("creating client...")
    client = google.cloud.bigtable_v2.BigtableClient()
    print("worker done")

if __name__ == "__main__":
    executor = concurrent.futures.ThreadPoolExecutor()
    futures_list = []
    for i in range(10):
        futures_list.append(executor.submit(bg_worker))
    for future in futures_list:
        future.result()
```

In both cases, I used would run python script in a bash loop. The Python code doesn't hang every time, but when looped, it will consistently hang within a couple minutes:

```
while true
do 
  python test_script.py
done
```

**Comment by parthea** [comment] 2024-04-07 13:14
Thanks for the sample code! I can produce the issue in versions of `grpcio` newer than 1.58.0

The issue does not appear with `pip install grpcio==1.58.0` . I'll try to create a minimal example using `gRPC` and file an issue in that repository.

**Comment by parthea** [comment] 2024-04-07 13:20
This could be related to https://github.com/grpc/grpc/issues/34672 which was fixed for `grpc_ssl_credentials_create`. There may be another code path in the gRPC code that still needs to be fixed.

**Comment by parthea** [comment] 2024-04-07 14:22
Marking as P2 since there is a workaround which is to use `grpcio==1.58.0`. I'll file an issue in the gRPC repository which we can use to track the long term fix.

**Comment by patjakdev** [comment] 2024-04-20 22:46
@parthea and @daniel-sanche - thanks to you both! Sorry I've gone a bit silent; I was on vacation the past two weeks.

If there's anything else I can do to help let me know, but it looks like y'all got to the bottom of this.

**Comment by daniel-sanche** [comment] 2024-04-24 23:57
Yeah I think it should be safe to close this, thanks for the detailed bug report!

**Closed by daniel-sanche** 2024-04-24 23:57 UTC
Labels: api: bigtable, type: bug, priority: p2
